### ISSUE TITLE
Exception in version for mysql 4.1

### ISSUE THREAD

**Issue by maninhat** [pmachapman/mysqltuner#11]
System.ArgumentException: Элемент с тем же ключом уже был добавлен.
   в System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   в MySqlTuner.MySqlServer.Load() в c:\Users\Peter\Documents\Visual Studio 2013\Projects\MySQLTuner\MySQLTuner\MySqlServer.cs:строка 372
   в MySqlTuner.FormMain.BackgroundWorker_DoWork(Object sender, DoWorkEventArgs e) в c:\Users\Peter\Documents\Visual Studio 2013\Projects\MySQLTuner\MySQLTuner\FormMain.cs:строка 369

**Comment by pmachapman** [comment]
Error in English is "An item with the same key has already been added".

**Comment by pmachapman** [comment]
Fixed in commit f01722526dee2086e75976ed97d898ee91b773d4
