### ISSUE TITLE
MySQL Tuner hangs during startup with "System.FormatException"

### ISSUE THREAD

**Issue by pmachapman** [pmachapman/mysqltuner#13]
Windows 2012R2 fully patched
MySQL 5.7.11 32bit

Starting MySQL Tuner the follwing error prevents the application to finish its start-up initialization:

System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
bei System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
bei System.Convert.ToDouble(String value, IFormatProvider provider)
bei MySqlTuner.TuningCalculator.MySqlStats() in c:\Documents and Settings\Administrator\My Documents\Source\mysqltuner\MySQLTuner\TuningCalculator.cs:Zeile 732.
bei MySqlTuner.TuningCalculator.Calculate(MySqlServer server) in c:\Documents and Settings\Administrator\My Documents\Source\mysqltuner\MySQLTuner\TuningCalculator.cs:Zeile 154.

Please find attached a screenshot of the application start-up sequence.

**Comment by pmachapman** [comment]
Add some more Information, though don't know if this is relevant:

    Windows Server 2012r2 does not come with directory c:\Documents and Settings* - Its either using c:\ProgramData* or c:\users*
    Installed .net framework version is 4.6 by default as windows 2012r2 does not support the 4.0 version

**Comment by duferic** [comment]
had the same problem... the answer for me was to change regional settings from french to english https://support.microsoft.com/en-us/kb/942460

**Comment by pmachapman** [comment]
Fixed in 052292b78c7b244dd213373c9c39345a3ccc0735
