### ISSUE TITLE
Support early mysql 4.0.18 issue

### ISSUE THREAD

**Issue by ayuen99** [pmachapman/mysqltuner#15]
Is there any solution for support mysql 4.0.18 ?

I got "connector/net no longer supports: server versions prior to 5.0" when execute it.

**Comment by pmachapman** [comment]
Did you try the alternate download? https://github.com/pmachapman/mysqltuner/releases/download/0.8.1/MySQLTuner-0.8.1-net20-connector-625.zip

**Comment by ayuen99** [comment]
My mysql server is 4.0.18.

Connector/Net no longer supports server verions prior to 4.1

**Comment by pmachapman** [comment]
Ok - I've made a version that should work with 4.0. I don't have a copy of MySQL 4.0 to run to test it - please let me know how you get on: https://github.com/pmachapman/mysqltuner/releases/download/0.8.1/MySQLTuner-0.8.1-net20-connector-517.zip

**Comment by ayuen99** [comment]
It can't work.

MySql.Data.MySqlClient.MySqlException: You have an error in your SQL syntax.  Check the manual that corresponds to your MySQL server version for the right syntax to use near 'ENGINES' at line 1
   MySql.Data.MySqlClient.MySqlStream.OpenPacket()
   MySql.Data.MySqlClient.NativeDriver.ReadResult(UInt64& affectedRows, Int64& lastInsertId)
   MySql.Data.MySqlClient.MySqlDataReader.GetResultSet()
   MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   MySqlTuner.MySqlServer.Load() C:\Users\peter\Source\Repos\mysqltuner\MySQLTuner\MySqlServer.cs: line 448
    MySqlTuner.TuningCalculator.Calculate(MySqlServer server) C:\Users\peter\Source\Repos\mysqltuner\MySQLTuner\TuningCalculator.cs: line 138

**Comment by ayuen99** [comment]
it can't work.

MySql.Data.MySqlClient.MySqlException: You have an error in your SQL syntax.  Check the manual that corresponds to your MySQL server version for the right syntax to use near 'ENGINES' at line 1
   at MySql.Data.MySqlClient.MySqlStream.OpenPacket()
   at MySql.Data.MySqlClient.NativeDriver.ReadResult(UInt64& affectedRows, Int64& lastInsertId)
   at MySql.Data.MySqlClient.MySqlDataReader.GetResultSet()
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySqlTuner.MySqlServer.Load() in C:\Users\peter\Source\Repos\mysqltuner\MySQLTuner\MySqlServer.cs:line 448
   at MySqlTuner.TuningCalculator.Calculate(MySqlServer server) in C:\Users\peter\Source\Repos\mysqltuner\MySQLTuner\TuningCalculator.cs:line 138

**Comment by ayuen99** [comment]
Can you fix it?

**Comment by pmachapman** [comment]
Not sure. Will need to set up a MySQL 4.0.18 server, then recreate the issue before I can fix it. I'll keep the ticket open until I can determine whether the issue can be fixed or not.

**Comment by pmachapman** [comment]
Fixed in d72dd4fe30b1c8df21526ecfe3635ef40de48ac6

**Comment by pmachapman** [comment]
I've installed MySQL 4.0 (not an easy task to find a copy...), and managed to track down and fix the bug.

Can you please try the latest package, and let me know how your get on: https://github.com/pmachapman/mysqltuner/releases/download/0.8.2/MySQLTuner-0.8.2-net20-connector-517.zip

**Comment by ayuen99** [comment]
It work fine. Thanks a lot.
