### ISSUE TITLE
KeyNotFound error

### ISSUE THREAD

**Issue by fmdelvalle** [pmachapman/mysqltuner#20]
Hi, the app gets blocked after showing this error:

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)   at MySqlTuner.TuningCalculator.PerformCalculations() in C:\Users\Peter.Chapman\Source\Repos\mysqltuner\MySQLTuner\TuningCalculator.cs:line 572   at MySqlTuner.TuningCalculator.Calculate(MySqlServer server) in C:\Users\Peter.Chapman\Source\Repos\mysqltuner\MySQLTuner\TuningCalculator.cs:line 150
--

I guess this special case could be controlled so it does not throw it...

Cheers

**Comment by pmachapman** [comment]
Hi,
What version of MySQL are you running so I can see if I can recreate the issue?

Thanks,


Peter

**Comment by fmdelvalle** [comment]
Hi, it's 8.0.13

**Comment by pmachapman** [comment]
Thanks - it looks like they have removed the query cache variables from MySQL 8.0 - see https://dev.mysql.com/doc/refman/8.0/en/added-deprecated-removed.html. I'll let you know when I have a fix ready for you.

**Comment by fmdelvalle** [comment]
Ok thanks!

**Comment by pmachapman** [comment]
Fixed in commit b964565e915d41200ab90ac51ed2fdac8c3c92d2.

**Comment by pmachapman** [comment]
Hi,
I have published this fix in the latest version (0.8.5), available from the repository home page and https://github.com/pmachapman/mysqltuner/releases/download/0.8.5/MySQLTuner-0.8.5.zip.

Please note that I have only fixed the crash - none of the recommendations have been optimised for MySQL 8.0. I suggest running the Perl script from http://mysqltuner.pl/ for more accurate results.

Thanks,


Peter
