### ISSUE TITLE
Character set 'utf8mb3' is not supported by .Net Framework.

### ISSUE THREAD

**Issue by baedaron** [pmachapman/mysqltuner#22]
Windows 10 (Korean)
MariaDB 10.6 (x64)

-------------------------------------------------------------------------------------------------------------------------------------------
MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Fatal error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.MySqlException (0x80004005): Character set 'utf8mb3' is not supported by .Net Framework.
   위치: MySql.Data.MySqlClient.CharSetMap.GetCharacterSet(DBVersion version, String CharSetName)
   위치: MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   위치: MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   위치: MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   위치: MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   위치: MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   위치: MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   위치: MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   위치: MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   위치: MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   위치: MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   위치: MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   위치: MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   위치: MySqlTuner.MySqlServer.Load() 파일 D:\source\repos\mysqltuner\MySQLTuner\MySqlServer.cs:줄 384
   위치: MySqlTuner.TuningCalculator.Calculate(MySqlServer server) 파일 D:\source\repos\mysqltuner\MySQLTuner\TuningCalculator.cs:줄 136

**Comment by pmachapman** [comment]
This might be connector/net version related. The following page will be helpful for sorting out the correct versions: https://dev.mysql.com/doc/connector-net/en/connector-net-versions.html

**Comment by pmachapman** [comment]
Fixed in commit [58bfac6](https://github.com/pmachapman/mysqltuner/commit/58bfac67deac97e826ebf3e3aa16867b6b2fda8a).

A fix for this issue will be released with 0.8.6.
